import React from "react";
import { 
  FaUserGraduate, 
  FaChalkboardTeacher, 
  FaUserShield, 
  FaClipboardCheck, 
  FaChartLine, 
  FaFileAlt, 
  FaBullhorn, 
  FaBrain, 
  FaLightbulb 
} from "react-icons/fa";
import "./About.css";

const About = () => {
  return (
    <div className="about-page">
      {/* Hero Section */}
      <section className="about-hero">
        <div className="hero-inner">
          <span className="hero-tag">Edu_web Ecosystem</span>
          <h1>Human Education for <span>Technical Excellence</span></h1>
          <p>
            A comprehensive management system integrating traditional academic workflows 
            with modern artificial intelligence to predict and enhance student success.
          </p>
        </div>
      </section>

      {/* Portals Section */}
      <section className="about-section">
        <h2 className="section-heading">Unified Portals</h2>
        <div className="cards-container">
          <div className="portal-card">
            <FaUserGraduate className="portal-icon" />
            <h3>Student</h3>
            <p>Monitor attendance, track grades, and view AI performance predictions in real-time.</p>
          </div>
          <div className="portal-card">
            <FaChalkboardTeacher className="portal-icon" />
            <h3>Faculty</h3>
            <p>Manage classrooms, automate grading, and broadcast notices to specific batches.</p>
          </div>
          <div className="portal-card">
            <FaUserShield className="portal-icon" />
            <h3>Admin</h3>
            <p>Full system oversight, user role management, and institutional data security.</p>
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section className="about-section dark-bg">
        <h2 className="section-heading">Core Management</h2>
        <div className="features-list">
          <div className="feature-row">
            <FaClipboardCheck className="feature-bullet" />
            <div>
              <h4>Attendance & Grading</h4>
              <p>Automated calculation of attendance percentages and GPA tracking.</p>
            </div>
          </div>
          <div className="feature-row">
            <FaFileAlt className="feature-bullet" />
            <div>
              <h4>Digital Assignments</h4>
              <p>Paperless submission system with integrated deadline management.</p>
            </div>
          </div>
          <div className="feature-row">
            <FaBullhorn className="feature-bullet" />
            <div>
              <h4>Notice Board</h4>
              <p>Instant digital alerts for exams, events, and academic updates.</p>
            </div>
          </div>
        </div>
      </section>

      {/* AI Section */}
      <section className="about-section ai-gradient">
        <h2 className="section-heading">AI & Intelligence</h2>
        <div className="ai-layout">
          <div className="ai-box">
            <FaBrain className="ai-icon" />
            <h3>ML Performance Prediction</h3>
            <p>Analyzes historical patterns to forecast final results, enabling early support for students at risk.</p>
          </div>
          <div className="ai-box">
            <FaLightbulb className="ai-icon" />
            <h3>Smart Study Recommendations</h3>
            <p>Tailored study paths generated by AI based on a student's individual performance gaps.</p>
          </div>
        </div>
      </section>
    </div>
  );
};

export default About;